---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2

suites:
  - name: tasks
    run_list:
      - recipe[fiddler::default]
      - recipe[minitest-handler]
