---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero

platforms:
  - name: windows2012r2
    driver:
      box: daptiv/windows2012r2_chef12
    driver_config:
      communicator: winrm
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[fiddler::default]
