source 'https://rubygems.org'

gem 'chef', '~> 11.8.0'
gem 'foodcritic', '>=3.0.0'
gem 'daptiv-foodcritic-rules'
gem 'tailor'
gem 'rake'
gem 'berkshelf', '~> 2.0.18'
gem 'minitest-chef-handler'
gem 'daptiv-chef-ci', '~> 0.0.13'
