name             'fiddler'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/fiddler'
issues_url       'https://github.com/windowschefcookbooks/fiddler/issues'
license          'Apache 2.0'
description      'Installs/Configures Fiddler'
version          '1.0.1'
